! *****************************COPYRIGHT*******************************
! (C) Crown copyright Met Office. All rights reserved.
! For further details please refer to the file COPYRIGHT.txt
! which you should have received as part of this distribution.
! *****************************COPYRIGHT*******************************

!    Routine: PR_F_C1A ------------------------------------------------
!
!    Purpose: To print messages generated by the I/O routines in C
!
!
!Code Owner: See Unified Model Code Owners HTML page
!This file belongs in section: Dump I/O

SUBROUTINE print_from_c(unit, message)

USE yomhook, ONLY: lhook, dr_hook
USE parkind1, ONLY: jprb, jpim
IMPLICIT NONE

INTEGER unit              ! the unit number that the message
                          ! applies to, or -1 if there is no
                          ! unit number.

CHARACTER(LEN=*) message     ! the text of the message

CHARACTER(LEN=384) old_message ! the text of the last message

INTEGER                                                           &
  old_unit                                                        &
                          ! the unit number for the last message
 ,i                                                               &
                          ! loop index
 ,message_count                                                   &
                          ! count of the number of times the last
                          ! message appeared, after the first time
 ,l                                                               &
                          ! length of the message from get_char_len
 ,old_l                   ! length of the old message

INTEGER(KIND=jpim), PARAMETER :: zhook_in  = 0
INTEGER(KIND=jpim), PARAMETER :: zhook_out = 1
REAL(KIND=jprb)               :: zhook_handle

SAVE old_unit, old_message, message_count
DATA old_unit/-2/, message_count/0/, old_l/1/,                    &
 old_message/'? ? ? ? ? ? ? ? ?'/

IF (lhook) CALL dr_hook('PRINT_FROM_C',zhook_in,zhook_handle)
l=LEN_TRIM(message)
IF (old_unit == unit .AND. old_message(1:l) == message(1:l)) THEN
  message_count=message_count+1
ELSE
  IF (message_count >  0) THEN
    WRITE(6,'(a,a,i3,a)')                                         &
          old_message(1:old_l),' - Repeated ',message_count,     &
          ' Time(s)' 
  END IF
  IF (unit /= old_unit) WRITE(6,'('' '')')
  WRITE(6,'(a)') message(1:l)
  message_count=0
  old_message=message
  old_l=l
  old_unit=unit
END IF

IF (lhook) CALL dr_hook('PRINT_FROM_C',zhook_out,zhook_handle)
RETURN
END SUBROUTINE print_from_c
